# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DBObject.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DBObject.proto',
  package='DBObj',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x44\x42Object.proto\x12\x05\x44\x42Obj\"\x96\x01\n\x0c\x44\x42PlayerBase\x12\x12\n\ncreatetime\x18\x01 \x01(\x03\x12\x12\n\nlogouttime\x18\x02 \x01(\x03\x12\x11\n\tlogintime\x18\x03 \x01(\x03\x12\r\n\x05ranks\x18\x04 \x01(\x05\x12\r\n\x05level\x18\x05 \x01(\x05\x12\r\n\x05honor\x18\x06 \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\x07 \x01(\x05\x12\x0e\n\x06golden\x18\x08 \x01(\x05\"\x1d\n\rDBPlayerFight\x12\x0c\n\x04text\x18\x01 \x01(\t\"b\n\x08\x44\x42Player\x12\x0e\n\x06userid\x18\x01 \x01(\x03\x12!\n\x04\x62\x61se\x18\x02 \x01(\x0b\x32\x13.DBObj.DBPlayerBase\x12#\n\x05\x66ight\x18\x03 \x01(\x0b\x32\x14.DBObj.DBPlayerFightb\x06proto3')
)




_DBPLAYERBASE = _descriptor.Descriptor(
  name='DBPlayerBase',
  full_name='DBObj.DBPlayerBase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='createtime', full_name='DBObj.DBPlayerBase.createtime', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='logouttime', full_name='DBObj.DBPlayerBase.logouttime', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='logintime', full_name='DBObj.DBPlayerBase.logintime', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ranks', full_name='DBObj.DBPlayerBase.ranks', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='DBObj.DBPlayerBase.level', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='honor', full_name='DBObj.DBPlayerBase.honor', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='DBObj.DBPlayerBase.action', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='golden', full_name='DBObj.DBPlayerBase.golden', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=176,
)


_DBPLAYERFIGHT = _descriptor.Descriptor(
  name='DBPlayerFight',
  full_name='DBObj.DBPlayerFight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='DBObj.DBPlayerFight.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=207,
)


_DBPLAYER = _descriptor.Descriptor(
  name='DBPlayer',
  full_name='DBObj.DBPlayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userid', full_name='DBObj.DBPlayer.userid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='base', full_name='DBObj.DBPlayer.base', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fight', full_name='DBObj.DBPlayer.fight', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=307,
)

_DBPLAYER.fields_by_name['base'].message_type = _DBPLAYERBASE
_DBPLAYER.fields_by_name['fight'].message_type = _DBPLAYERFIGHT
DESCRIPTOR.message_types_by_name['DBPlayerBase'] = _DBPLAYERBASE
DESCRIPTOR.message_types_by_name['DBPlayerFight'] = _DBPLAYERFIGHT
DESCRIPTOR.message_types_by_name['DBPlayer'] = _DBPLAYER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DBPlayerBase = _reflection.GeneratedProtocolMessageType('DBPlayerBase', (_message.Message,), {
  'DESCRIPTOR' : _DBPLAYERBASE,
  '__module__' : 'DBObject_pb2'
  # @@protoc_insertion_point(class_scope:DBObj.DBPlayerBase)
  })
_sym_db.RegisterMessage(DBPlayerBase)

DBPlayerFight = _reflection.GeneratedProtocolMessageType('DBPlayerFight', (_message.Message,), {
  'DESCRIPTOR' : _DBPLAYERFIGHT,
  '__module__' : 'DBObject_pb2'
  # @@protoc_insertion_point(class_scope:DBObj.DBPlayerFight)
  })
_sym_db.RegisterMessage(DBPlayerFight)

DBPlayer = _reflection.GeneratedProtocolMessageType('DBPlayer', (_message.Message,), {
  'DESCRIPTOR' : _DBPLAYER,
  '__module__' : 'DBObject_pb2'
  # @@protoc_insertion_point(class_scope:DBObj.DBPlayer)
  })
_sym_db.RegisterMessage(DBPlayer)


# @@protoc_insertion_point(module_scope)
