# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageSkill.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageSkill.proto',
  package='',
  serialized_pb=_b('\n\x12MessageSkill.proto\"\"\n\x0cS2CSkillList\x12\x12\n\nskill_list\x18\x01 \x03(\x05\"_\n\x0bS2CBaseGong\x12\x0c\n\x04pos1\x18\x01 \x02(\x05\x12\x0c\n\x04pos2\x18\x02 \x02(\x05\x12\x0c\n\x04pos3\x18\x03 \x02(\x05\x12\x11\n\tlastpoint\x18\x04 \x02(\x05\x12\x13\n\x0breset_count\x18\x05 \x02(\x05\"N\n\x0cS2CHeartGong\x12\x0e\n\x06heart1\x18\x01 \x02(\x05\x12\x0e\n\x06heart2\x18\x02 \x02(\x05\x12\x0e\n\x06heart3\x18\x03 \x02(\x05\x12\x0e\n\x06heart4\x18\x04 \x02(\x05\"2\n\x0f\x43\x32SSkillUpgrade\x12\r\n\x05level\x18\x01 \x02(\x05\x12\x10\n\x08skill_id\x18\x02 \x01(\x05\"2\n\x13\x43\x32SUpgradeHeartGong\x12\x0c\n\x04type\x18\x01 \x02(\x05\x12\r\n\x05index\x18\x02 \x02(\x05\"Q\n\x13\x43\x32SAddBaseGongPoint\x12\x12\n\npos1_point\x18\x01 \x02(\x05\x12\x12\n\npos2_point\x18\x02 \x02(\x05\x12\x12\n\npos3_point\x18\x03 \x02(\x05\"\x16\n\x14\x43\x32ResetBaseGongPoint')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_S2CSKILLLIST = _descriptor.Descriptor(
  name='S2CSkillList',
  full_name='S2CSkillList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='skill_list', full_name='S2CSkillList.skill_list', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=56,
)


_S2CBASEGONG = _descriptor.Descriptor(
  name='S2CBaseGong',
  full_name='S2CBaseGong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos1', full_name='S2CBaseGong.pos1', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos2', full_name='S2CBaseGong.pos2', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos3', full_name='S2CBaseGong.pos3', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastpoint', full_name='S2CBaseGong.lastpoint', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reset_count', full_name='S2CBaseGong.reset_count', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=153,
)


_S2CHEARTGONG = _descriptor.Descriptor(
  name='S2CHeartGong',
  full_name='S2CHeartGong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='heart1', full_name='S2CHeartGong.heart1', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heart2', full_name='S2CHeartGong.heart2', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heart3', full_name='S2CHeartGong.heart3', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heart4', full_name='S2CHeartGong.heart4', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=233,
)


_C2SSKILLUPGRADE = _descriptor.Descriptor(
  name='C2SSkillUpgrade',
  full_name='C2SSkillUpgrade',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='C2SSkillUpgrade.level', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skill_id', full_name='C2SSkillUpgrade.skill_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=285,
)


_C2SUPGRADEHEARTGONG = _descriptor.Descriptor(
  name='C2SUpgradeHeartGong',
  full_name='C2SUpgradeHeartGong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='C2SUpgradeHeartGong.type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index', full_name='C2SUpgradeHeartGong.index', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=337,
)


_C2SADDBASEGONGPOINT = _descriptor.Descriptor(
  name='C2SAddBaseGongPoint',
  full_name='C2SAddBaseGongPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos1_point', full_name='C2SAddBaseGongPoint.pos1_point', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos2_point', full_name='C2SAddBaseGongPoint.pos2_point', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos3_point', full_name='C2SAddBaseGongPoint.pos3_point', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=420,
)


_C2RESETBASEGONGPOINT = _descriptor.Descriptor(
  name='C2ResetBaseGongPoint',
  full_name='C2ResetBaseGongPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=422,
  serialized_end=444,
)

DESCRIPTOR.message_types_by_name['S2CSkillList'] = _S2CSKILLLIST
DESCRIPTOR.message_types_by_name['S2CBaseGong'] = _S2CBASEGONG
DESCRIPTOR.message_types_by_name['S2CHeartGong'] = _S2CHEARTGONG
DESCRIPTOR.message_types_by_name['C2SSkillUpgrade'] = _C2SSKILLUPGRADE
DESCRIPTOR.message_types_by_name['C2SUpgradeHeartGong'] = _C2SUPGRADEHEARTGONG
DESCRIPTOR.message_types_by_name['C2SAddBaseGongPoint'] = _C2SADDBASEGONGPOINT
DESCRIPTOR.message_types_by_name['C2ResetBaseGongPoint'] = _C2RESETBASEGONGPOINT

S2CSkillList = _reflection.GeneratedProtocolMessageType('S2CSkillList', (_message.Message,), dict(
  DESCRIPTOR = _S2CSKILLLIST,
  __module__ = 'MessageSkill_pb2'
  # @@protoc_insertion_point(class_scope:S2CSkillList)
  ))
_sym_db.RegisterMessage(S2CSkillList)

S2CBaseGong = _reflection.GeneratedProtocolMessageType('S2CBaseGong', (_message.Message,), dict(
  DESCRIPTOR = _S2CBASEGONG,
  __module__ = 'MessageSkill_pb2'
  # @@protoc_insertion_point(class_scope:S2CBaseGong)
  ))
_sym_db.RegisterMessage(S2CBaseGong)

S2CHeartGong = _reflection.GeneratedProtocolMessageType('S2CHeartGong', (_message.Message,), dict(
  DESCRIPTOR = _S2CHEARTGONG,
  __module__ = 'MessageSkill_pb2'
  # @@protoc_insertion_point(class_scope:S2CHeartGong)
  ))
_sym_db.RegisterMessage(S2CHeartGong)

C2SSkillUpgrade = _reflection.GeneratedProtocolMessageType('C2SSkillUpgrade', (_message.Message,), dict(
  DESCRIPTOR = _C2SSKILLUPGRADE,
  __module__ = 'MessageSkill_pb2'
  # @@protoc_insertion_point(class_scope:C2SSkillUpgrade)
  ))
_sym_db.RegisterMessage(C2SSkillUpgrade)

C2SUpgradeHeartGong = _reflection.GeneratedProtocolMessageType('C2SUpgradeHeartGong', (_message.Message,), dict(
  DESCRIPTOR = _C2SUPGRADEHEARTGONG,
  __module__ = 'MessageSkill_pb2'
  # @@protoc_insertion_point(class_scope:C2SUpgradeHeartGong)
  ))
_sym_db.RegisterMessage(C2SUpgradeHeartGong)

C2SAddBaseGongPoint = _reflection.GeneratedProtocolMessageType('C2SAddBaseGongPoint', (_message.Message,), dict(
  DESCRIPTOR = _C2SADDBASEGONGPOINT,
  __module__ = 'MessageSkill_pb2'
  # @@protoc_insertion_point(class_scope:C2SAddBaseGongPoint)
  ))
_sym_db.RegisterMessage(C2SAddBaseGongPoint)

C2ResetBaseGongPoint = _reflection.GeneratedProtocolMessageType('C2ResetBaseGongPoint', (_message.Message,), dict(
  DESCRIPTOR = _C2RESETBASEGONGPOINT,
  __module__ = 'MessageSkill_pb2'
  # @@protoc_insertion_point(class_scope:C2ResetBaseGongPoint)
  ))
_sym_db.RegisterMessage(C2ResetBaseGongPoint)


# @@protoc_insertion_point(module_scope)
