# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageGM.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageGM.proto',
  package='',
  serialized_pb=_b('\n\x0fMessageGM.proto\"\x1f\n\x0c\x43\x32SGMCommond\x12\x0f\n\x07\x63ommond\x18\x01 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_C2SGMCOMMOND = _descriptor.Descriptor(
  name='C2SGMCommond',
  full_name='C2SGMCommond',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='commond', full_name='C2SGMCommond.commond', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=50,
)

DESCRIPTOR.message_types_by_name['C2SGMCommond'] = _C2SGMCOMMOND

C2SGMCommond = _reflection.GeneratedProtocolMessageType('C2SGMCommond', (_message.Message,), dict(
  DESCRIPTOR = _C2SGMCOMMOND,
  __module__ = 'MessageGM_pb2'
  # @@protoc_insertion_point(class_scope:C2SGMCommond)
  ))
_sym_db.RegisterMessage(C2SGMCommond)


# @@protoc_insertion_point(module_scope)
