# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageTypeDefine.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageTypeDefine.proto',
  package='Message',
  serialized_pb=_b('\n\x17MessageTypeDefine.proto\x12\x07Message*\xfd\x02\n\tMsgDefine\x12\x11\n\rS2C_MSG_BEGIN\x10\x00\x12\x14\n\x10S2C_COMMON_ERROR\x10\x32\x12\x15\n\x11S2C_COMMON_NOTICE\x10\x33\x12\x18\n\x14S2C_COMMON_BROADCAST\x10\x34\x12\x12\n\x0eS2C_USER_LOGIN\x10\x64\x12\x13\n\x0fS2C_USER_LOGOUT\x10\x65\x12\x16\n\x12S2C_USER_HEARTBEAT\x10\x66\x12\x14\n\x10S2C_PLAYER_LOGIN\x10g\x12\x13\n\x0fS2C_PLAYER_INFO\x10h\x12\x10\n\x0bS2C_MSG_END\x10\x8fN\x12\x12\n\rC2S_MSG_BEGIN\x10\x90N\x12\x13\n\x0e\x43\x32S_USER_LOGIN\x10\x91N\x12\x14\n\x0f\x43\x32S_USER_LOGOUT\x10\x92N\x12\x17\n\x12\x43\x32S_USER_HEARTBEAT\x10\x93N\x12\x15\n\x10\x43\x32S_PLAYER_LOGIN\x10\x94N\x12\x16\n\x11\x43\x32S_PLAYER_LOGOUT\x10\x95N\x12\x11\n\x0b\x43\x32S_MSG_END\x10\xb0\xea\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_MSGDEFINE = _descriptor.EnumDescriptor(
  name='MsgDefine',
  full_name='Message.MsgDefine',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='S2C_MSG_BEGIN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S2C_COMMON_ERROR', index=1, number=50,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S2C_COMMON_NOTICE', index=2, number=51,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S2C_COMMON_BROADCAST', index=3, number=52,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S2C_USER_LOGIN', index=4, number=100,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S2C_USER_LOGOUT', index=5, number=101,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S2C_USER_HEARTBEAT', index=6, number=102,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S2C_PLAYER_LOGIN', index=7, number=103,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S2C_PLAYER_INFO', index=8, number=104,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S2C_MSG_END', index=9, number=9999,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='C2S_MSG_BEGIN', index=10, number=10000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='C2S_USER_LOGIN', index=11, number=10001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='C2S_USER_LOGOUT', index=12, number=10002,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='C2S_USER_HEARTBEAT', index=13, number=10003,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='C2S_PLAYER_LOGIN', index=14, number=10004,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='C2S_PLAYER_LOGOUT', index=15, number=10005,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='C2S_MSG_END', index=16, number=30000,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=37,
  serialized_end=418,
)
_sym_db.RegisterEnumDescriptor(_MSGDEFINE)

MsgDefine = enum_type_wrapper.EnumTypeWrapper(_MSGDEFINE)
S2C_MSG_BEGIN = 0
S2C_COMMON_ERROR = 50
S2C_COMMON_NOTICE = 51
S2C_COMMON_BROADCAST = 52
S2C_USER_LOGIN = 100
S2C_USER_LOGOUT = 101
S2C_USER_HEARTBEAT = 102
S2C_PLAYER_LOGIN = 103
S2C_PLAYER_INFO = 104
S2C_MSG_END = 9999
C2S_MSG_BEGIN = 10000
C2S_USER_LOGIN = 10001
C2S_USER_LOGOUT = 10002
C2S_USER_HEARTBEAT = 10003
C2S_PLAYER_LOGIN = 10004
C2S_PLAYER_LOGOUT = 10005
C2S_MSG_END = 30000


DESCRIPTOR.enum_types_by_name['MsgDefine'] = _MSGDEFINE


# @@protoc_insertion_point(module_scope)
