# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageClimbTower.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageClimbTower.proto',
  package='',
  serialized_pb=_b('\n\x17MessageClimbTower.proto\"A\n\x0cS2CTowerInfo\x12\x0e\n\x06\x63urnum\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x05\x12\x12\n\nresetcount\x18\x03 \x01(\x05\"\x0f\n\rC2STowerFight\"\x0f\n\rC2SResetTower')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_S2CTOWERINFO = _descriptor.Descriptor(
  name='S2CTowerInfo',
  full_name='S2CTowerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='curnum', full_name='S2CTowerInfo.curnum', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='S2CTowerInfo.score', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resetcount', full_name='S2CTowerInfo.resetcount', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=92,
)


_C2STOWERFIGHT = _descriptor.Descriptor(
  name='C2STowerFight',
  full_name='C2STowerFight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=109,
)


_C2SRESETTOWER = _descriptor.Descriptor(
  name='C2SResetTower',
  full_name='C2SResetTower',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['S2CTowerInfo'] = _S2CTOWERINFO
DESCRIPTOR.message_types_by_name['C2STowerFight'] = _C2STOWERFIGHT
DESCRIPTOR.message_types_by_name['C2SResetTower'] = _C2SRESETTOWER

S2CTowerInfo = _reflection.GeneratedProtocolMessageType('S2CTowerInfo', (_message.Message,), dict(
  DESCRIPTOR = _S2CTOWERINFO,
  __module__ = 'MessageClimbTower_pb2'
  # @@protoc_insertion_point(class_scope:S2CTowerInfo)
  ))
_sym_db.RegisterMessage(S2CTowerInfo)

C2STowerFight = _reflection.GeneratedProtocolMessageType('C2STowerFight', (_message.Message,), dict(
  DESCRIPTOR = _C2STOWERFIGHT,
  __module__ = 'MessageClimbTower_pb2'
  # @@protoc_insertion_point(class_scope:C2STowerFight)
  ))
_sym_db.RegisterMessage(C2STowerFight)

C2SResetTower = _reflection.GeneratedProtocolMessageType('C2SResetTower', (_message.Message,), dict(
  DESCRIPTOR = _C2SRESETTOWER,
  __module__ = 'MessageClimbTower_pb2'
  # @@protoc_insertion_point(class_scope:C2SResetTower)
  ))
_sym_db.RegisterMessage(C2SResetTower)


# @@protoc_insertion_point(module_scope)
