# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageGuild.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageGuild.proto',
  package='',
  serialized_pb=_b('\n\x12MessageGuild.proto\"\x1e\n\x0e\x43\x32SGuildCreate\x12\x0c\n\x04name\x18\x01 \x02(\t\"!\n\rC2SGuildApply\x12\x10\n\x08guild_id\x18\x01 \x02(\x05\"7\n\x0e\x43\x32SGuildInvite\x12\x13\n\x0bplayer_name\x18\x01 \x02(\t\x12\x10\n\x08guild_id\x18\x02 \x02(\x05\"&\n\x12\x43\x32SGuildAgreeApply\x12\x10\n\x08guild_id\x18\x02 \x02(\x05\"\'\n\x13\x43\x32SGuildAgreeInvite\x12\x10\n\x08guild_id\x18\x02 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_C2SGUILDCREATE = _descriptor.Descriptor(
  name='C2SGuildCreate',
  full_name='C2SGuildCreate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='C2SGuildCreate.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=52,
)


_C2SGUILDAPPLY = _descriptor.Descriptor(
  name='C2SGuildApply',
  full_name='C2SGuildApply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='guild_id', full_name='C2SGuildApply.guild_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=87,
)


_C2SGUILDINVITE = _descriptor.Descriptor(
  name='C2SGuildInvite',
  full_name='C2SGuildInvite',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_name', full_name='C2SGuildInvite.player_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='guild_id', full_name='C2SGuildInvite.guild_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=144,
)


_C2SGUILDAGREEAPPLY = _descriptor.Descriptor(
  name='C2SGuildAgreeApply',
  full_name='C2SGuildAgreeApply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='guild_id', full_name='C2SGuildAgreeApply.guild_id', index=0,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=184,
)


_C2SGUILDAGREEINVITE = _descriptor.Descriptor(
  name='C2SGuildAgreeInvite',
  full_name='C2SGuildAgreeInvite',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='guild_id', full_name='C2SGuildAgreeInvite.guild_id', index=0,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=225,
)

DESCRIPTOR.message_types_by_name['C2SGuildCreate'] = _C2SGUILDCREATE
DESCRIPTOR.message_types_by_name['C2SGuildApply'] = _C2SGUILDAPPLY
DESCRIPTOR.message_types_by_name['C2SGuildInvite'] = _C2SGUILDINVITE
DESCRIPTOR.message_types_by_name['C2SGuildAgreeApply'] = _C2SGUILDAGREEAPPLY
DESCRIPTOR.message_types_by_name['C2SGuildAgreeInvite'] = _C2SGUILDAGREEINVITE

C2SGuildCreate = _reflection.GeneratedProtocolMessageType('C2SGuildCreate', (_message.Message,), dict(
  DESCRIPTOR = _C2SGUILDCREATE,
  __module__ = 'MessageGuild_pb2'
  # @@protoc_insertion_point(class_scope:C2SGuildCreate)
  ))
_sym_db.RegisterMessage(C2SGuildCreate)

C2SGuildApply = _reflection.GeneratedProtocolMessageType('C2SGuildApply', (_message.Message,), dict(
  DESCRIPTOR = _C2SGUILDAPPLY,
  __module__ = 'MessageGuild_pb2'
  # @@protoc_insertion_point(class_scope:C2SGuildApply)
  ))
_sym_db.RegisterMessage(C2SGuildApply)

C2SGuildInvite = _reflection.GeneratedProtocolMessageType('C2SGuildInvite', (_message.Message,), dict(
  DESCRIPTOR = _C2SGUILDINVITE,
  __module__ = 'MessageGuild_pb2'
  # @@protoc_insertion_point(class_scope:C2SGuildInvite)
  ))
_sym_db.RegisterMessage(C2SGuildInvite)

C2SGuildAgreeApply = _reflection.GeneratedProtocolMessageType('C2SGuildAgreeApply', (_message.Message,), dict(
  DESCRIPTOR = _C2SGUILDAGREEAPPLY,
  __module__ = 'MessageGuild_pb2'
  # @@protoc_insertion_point(class_scope:C2SGuildAgreeApply)
  ))
_sym_db.RegisterMessage(C2SGuildAgreeApply)

C2SGuildAgreeInvite = _reflection.GeneratedProtocolMessageType('C2SGuildAgreeInvite', (_message.Message,), dict(
  DESCRIPTOR = _C2SGUILDAGREEINVITE,
  __module__ = 'MessageGuild_pb2'
  # @@protoc_insertion_point(class_scope:C2SGuildAgreeInvite)
  ))
_sym_db.RegisterMessage(C2SGuildAgreeInvite)


# @@protoc_insertion_point(module_scope)
