# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessagePet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessagePet.proto',
  package='',
  serialized_pb=_b('\n\x10MessagePet.proto\"\x88\x02\n\x07PetInfo\x12\x0b\n\x03tid\x18\x01 \x01(\x05\x12\r\n\x05level\x18\x02 \x01(\x05\x12\x0b\n\x03\x65xp\x18\x03 \x01(\x05\x12\x0f\n\x07quality\x18\x04 \x01(\x05\x12\x10\n\x08starlist\x18\x05 \x03(\x05\x12\n\n\x02hp\x18\x06 \x01(\x05\x12\x12\n\nphysattack\x18\x07 \x01(\x05\x12\x13\n\x0bmagicattack\x18\x08 \x01(\x05\x12\x12\n\nphysdefend\x18\t \x01(\x05\x12\x13\n\x0bmagicdefend\x18\n \x01(\x05\x12\r\n\x05speed\x18\x0b \x01(\x05\x12\x0f\n\x07sealhit\x18\x0c \x01(\x05\x12\x12\n\nsealresist\x18\r \x01(\x05\x12\r\n\x05treat\x18\x0e \x01(\x05\x12\x10\n\x08\x66ighting\x18\x0f \x01(\x05\":\n\nS2CPetList\x12\x19\n\x07petlist\x18\x01 \x03(\x0b\x32\x08.PetInfo\x12\x11\n\tfight_pet\x18\x02 \x01(\x05\"$\n\nS2CPetInfo\x12\x16\n\x04info\x18\x01 \x01(\x0b\x32\x08.PetInfo\" \n\x0e\x43\x32SSetFightPet\x12\x0e\n\x06pet_id\x18\x01 \x01(\x05\"\x1f\n\rC2SUpgradePet\x12\x0e\n\x06pet_id\x18\x01 \x01(\x05\" \n\x0e\x43\x32SExchangePet\x12\x0e\n\x06pet_id\x18\x01 \x01(\x05\"4\n\x11\x43\x32SUpgradePetStar\x12\x0e\n\x06pet_id\x18\x01 \x01(\x05\x12\x0f\n\x07star_id\x18\x02 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PETINFO = _descriptor.Descriptor(
  name='PetInfo',
  full_name='PetInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tid', full_name='PetInfo.tid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='PetInfo.level', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exp', full_name='PetInfo.exp', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quality', full_name='PetInfo.quality', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='starlist', full_name='PetInfo.starlist', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hp', full_name='PetInfo.hp', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='physattack', full_name='PetInfo.physattack', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='magicattack', full_name='PetInfo.magicattack', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='physdefend', full_name='PetInfo.physdefend', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='magicdefend', full_name='PetInfo.magicdefend', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='PetInfo.speed', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sealhit', full_name='PetInfo.sealhit', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sealresist', full_name='PetInfo.sealresist', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='treat', full_name='PetInfo.treat', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fighting', full_name='PetInfo.fighting', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=285,
)


_S2CPETLIST = _descriptor.Descriptor(
  name='S2CPetList',
  full_name='S2CPetList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='petlist', full_name='S2CPetList.petlist', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fight_pet', full_name='S2CPetList.fight_pet', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=345,
)


_S2CPETINFO = _descriptor.Descriptor(
  name='S2CPetInfo',
  full_name='S2CPetInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='S2CPetInfo.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=383,
)


_C2SSETFIGHTPET = _descriptor.Descriptor(
  name='C2SSetFightPet',
  full_name='C2SSetFightPet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pet_id', full_name='C2SSetFightPet.pet_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=417,
)


_C2SUPGRADEPET = _descriptor.Descriptor(
  name='C2SUpgradePet',
  full_name='C2SUpgradePet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pet_id', full_name='C2SUpgradePet.pet_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=419,
  serialized_end=450,
)


_C2SEXCHANGEPET = _descriptor.Descriptor(
  name='C2SExchangePet',
  full_name='C2SExchangePet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pet_id', full_name='C2SExchangePet.pet_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=452,
  serialized_end=484,
)


_C2SUPGRADEPETSTAR = _descriptor.Descriptor(
  name='C2SUpgradePetStar',
  full_name='C2SUpgradePetStar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pet_id', full_name='C2SUpgradePetStar.pet_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='star_id', full_name='C2SUpgradePetStar.star_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=486,
  serialized_end=538,
)

_S2CPETLIST.fields_by_name['petlist'].message_type = _PETINFO
_S2CPETINFO.fields_by_name['info'].message_type = _PETINFO
DESCRIPTOR.message_types_by_name['PetInfo'] = _PETINFO
DESCRIPTOR.message_types_by_name['S2CPetList'] = _S2CPETLIST
DESCRIPTOR.message_types_by_name['S2CPetInfo'] = _S2CPETINFO
DESCRIPTOR.message_types_by_name['C2SSetFightPet'] = _C2SSETFIGHTPET
DESCRIPTOR.message_types_by_name['C2SUpgradePet'] = _C2SUPGRADEPET
DESCRIPTOR.message_types_by_name['C2SExchangePet'] = _C2SEXCHANGEPET
DESCRIPTOR.message_types_by_name['C2SUpgradePetStar'] = _C2SUPGRADEPETSTAR

PetInfo = _reflection.GeneratedProtocolMessageType('PetInfo', (_message.Message,), dict(
  DESCRIPTOR = _PETINFO,
  __module__ = 'MessagePet_pb2'
  # @@protoc_insertion_point(class_scope:PetInfo)
  ))
_sym_db.RegisterMessage(PetInfo)

S2CPetList = _reflection.GeneratedProtocolMessageType('S2CPetList', (_message.Message,), dict(
  DESCRIPTOR = _S2CPETLIST,
  __module__ = 'MessagePet_pb2'
  # @@protoc_insertion_point(class_scope:S2CPetList)
  ))
_sym_db.RegisterMessage(S2CPetList)

S2CPetInfo = _reflection.GeneratedProtocolMessageType('S2CPetInfo', (_message.Message,), dict(
  DESCRIPTOR = _S2CPETINFO,
  __module__ = 'MessagePet_pb2'
  # @@protoc_insertion_point(class_scope:S2CPetInfo)
  ))
_sym_db.RegisterMessage(S2CPetInfo)

C2SSetFightPet = _reflection.GeneratedProtocolMessageType('C2SSetFightPet', (_message.Message,), dict(
  DESCRIPTOR = _C2SSETFIGHTPET,
  __module__ = 'MessagePet_pb2'
  # @@protoc_insertion_point(class_scope:C2SSetFightPet)
  ))
_sym_db.RegisterMessage(C2SSetFightPet)

C2SUpgradePet = _reflection.GeneratedProtocolMessageType('C2SUpgradePet', (_message.Message,), dict(
  DESCRIPTOR = _C2SUPGRADEPET,
  __module__ = 'MessagePet_pb2'
  # @@protoc_insertion_point(class_scope:C2SUpgradePet)
  ))
_sym_db.RegisterMessage(C2SUpgradePet)

C2SExchangePet = _reflection.GeneratedProtocolMessageType('C2SExchangePet', (_message.Message,), dict(
  DESCRIPTOR = _C2SEXCHANGEPET,
  __module__ = 'MessagePet_pb2'
  # @@protoc_insertion_point(class_scope:C2SExchangePet)
  ))
_sym_db.RegisterMessage(C2SExchangePet)

C2SUpgradePetStar = _reflection.GeneratedProtocolMessageType('C2SUpgradePetStar', (_message.Message,), dict(
  DESCRIPTOR = _C2SUPGRADEPETSTAR,
  __module__ = 'MessagePet_pb2'
  # @@protoc_insertion_point(class_scope:C2SUpgradePetStar)
  ))
_sym_db.RegisterMessage(C2SUpgradePetStar)


# @@protoc_insertion_point(module_scope)
