# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageArena.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageArena.proto',
  package='Message',
  serialized_pb=_b('\n\x12MessageArena.proto\x12\x07Message\"W\n\x0b\x41renaPlayer\x12\x0b\n\x03pid\x18\x01 \x01(\t\x12\x0c\n\x04rank\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05level\x18\x04 \x01(\x05\x12\x10\n\x08\x66ighting\x18\x05 \x01(\x05\"p\n\nArenaFight\x12\x10\n\x08\x61ttacker\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65\x66\x65nder\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\t\x12\x0f\n\x07oldrank\x18\x04 \x01(\x05\x12\x0f\n\x07newrank\x18\x05 \x01(\x05\x12\x0e\n\x06result\x18\x06 \x01(\x08\"*\n\rC2SArenaFight\x12\x0b\n\x03pid\x18\x01 \x01(\x03\x12\x0c\n\x04rank\x18\x02 \x01(\x05\"\x0f\n\rC2SArenaEnter\"\x11\n\x0f\x43\x32SArenaToplist\"\x13\n\x11\x43\x32SArenaRankPrize\";\n\x0fS2CArenaToplist\x12(\n\nplayerlist\x18\x01 \x03(\x0b\x32\x14.Message.ArenaPlayer\">\n\x12S2CArenaTargetlist\x12(\n\nplayerlist\x18\x01 \x03(\x0b\x32\x14.Message.ArenaPlayer\"\x80\x01\n\x12S2CArenaPlayerInfo\x12\x0c\n\x04rank\x18\x01 \x01(\x05\x12\x10\n\x08lastrank\x18\x02 \x01(\x05\x12\r\n\x05prize\x18\x03 \x01(\x05\x12\x13\n\x0b\x61ttackcount\x18\x04 \x01(\x05\x12&\n\tfightlist\x18\x05 \x03(\x0b\x32\x13.Message.ArenaFight')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ARENAPLAYER = _descriptor.Descriptor(
  name='ArenaPlayer',
  full_name='Message.ArenaPlayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='Message.ArenaPlayer.pid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rank', full_name='Message.ArenaPlayer.rank', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Message.ArenaPlayer.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='Message.ArenaPlayer.level', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fighting', full_name='Message.ArenaPlayer.fighting', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=118,
)


_ARENAFIGHT = _descriptor.Descriptor(
  name='ArenaFight',
  full_name='Message.ArenaFight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attacker', full_name='Message.ArenaFight.attacker', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='defender', full_name='Message.ArenaFight.defender', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='Message.ArenaFight.time', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oldrank', full_name='Message.ArenaFight.oldrank', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='newrank', full_name='Message.ArenaFight.newrank', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='Message.ArenaFight.result', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=232,
)


_C2SARENAFIGHT = _descriptor.Descriptor(
  name='C2SArenaFight',
  full_name='Message.C2SArenaFight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='Message.C2SArenaFight.pid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rank', full_name='Message.C2SArenaFight.rank', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=276,
)


_C2SARENAENTER = _descriptor.Descriptor(
  name='C2SArenaEnter',
  full_name='Message.C2SArenaEnter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=293,
)


_C2SARENATOPLIST = _descriptor.Descriptor(
  name='C2SArenaToplist',
  full_name='Message.C2SArenaToplist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=312,
)


_C2SARENARANKPRIZE = _descriptor.Descriptor(
  name='C2SArenaRankPrize',
  full_name='Message.C2SArenaRankPrize',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=333,
)


_S2CARENATOPLIST = _descriptor.Descriptor(
  name='S2CArenaToplist',
  full_name='Message.S2CArenaToplist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerlist', full_name='Message.S2CArenaToplist.playerlist', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=394,
)


_S2CARENATARGETLIST = _descriptor.Descriptor(
  name='S2CArenaTargetlist',
  full_name='Message.S2CArenaTargetlist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerlist', full_name='Message.S2CArenaTargetlist.playerlist', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=458,
)


_S2CARENAPLAYERINFO = _descriptor.Descriptor(
  name='S2CArenaPlayerInfo',
  full_name='Message.S2CArenaPlayerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rank', full_name='Message.S2CArenaPlayerInfo.rank', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastrank', full_name='Message.S2CArenaPlayerInfo.lastrank', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prize', full_name='Message.S2CArenaPlayerInfo.prize', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attackcount', full_name='Message.S2CArenaPlayerInfo.attackcount', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fightlist', full_name='Message.S2CArenaPlayerInfo.fightlist', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=461,
  serialized_end=589,
)

_S2CARENATOPLIST.fields_by_name['playerlist'].message_type = _ARENAPLAYER
_S2CARENATARGETLIST.fields_by_name['playerlist'].message_type = _ARENAPLAYER
_S2CARENAPLAYERINFO.fields_by_name['fightlist'].message_type = _ARENAFIGHT
DESCRIPTOR.message_types_by_name['ArenaPlayer'] = _ARENAPLAYER
DESCRIPTOR.message_types_by_name['ArenaFight'] = _ARENAFIGHT
DESCRIPTOR.message_types_by_name['C2SArenaFight'] = _C2SARENAFIGHT
DESCRIPTOR.message_types_by_name['C2SArenaEnter'] = _C2SARENAENTER
DESCRIPTOR.message_types_by_name['C2SArenaToplist'] = _C2SARENATOPLIST
DESCRIPTOR.message_types_by_name['C2SArenaRankPrize'] = _C2SARENARANKPRIZE
DESCRIPTOR.message_types_by_name['S2CArenaToplist'] = _S2CARENATOPLIST
DESCRIPTOR.message_types_by_name['S2CArenaTargetlist'] = _S2CARENATARGETLIST
DESCRIPTOR.message_types_by_name['S2CArenaPlayerInfo'] = _S2CARENAPLAYERINFO

ArenaPlayer = _reflection.GeneratedProtocolMessageType('ArenaPlayer', (_message.Message,), dict(
  DESCRIPTOR = _ARENAPLAYER,
  __module__ = 'MessageArena_pb2'
  # @@protoc_insertion_point(class_scope:Message.ArenaPlayer)
  ))
_sym_db.RegisterMessage(ArenaPlayer)

ArenaFight = _reflection.GeneratedProtocolMessageType('ArenaFight', (_message.Message,), dict(
  DESCRIPTOR = _ARENAFIGHT,
  __module__ = 'MessageArena_pb2'
  # @@protoc_insertion_point(class_scope:Message.ArenaFight)
  ))
_sym_db.RegisterMessage(ArenaFight)

C2SArenaFight = _reflection.GeneratedProtocolMessageType('C2SArenaFight', (_message.Message,), dict(
  DESCRIPTOR = _C2SARENAFIGHT,
  __module__ = 'MessageArena_pb2'
  # @@protoc_insertion_point(class_scope:Message.C2SArenaFight)
  ))
_sym_db.RegisterMessage(C2SArenaFight)

C2SArenaEnter = _reflection.GeneratedProtocolMessageType('C2SArenaEnter', (_message.Message,), dict(
  DESCRIPTOR = _C2SARENAENTER,
  __module__ = 'MessageArena_pb2'
  # @@protoc_insertion_point(class_scope:Message.C2SArenaEnter)
  ))
_sym_db.RegisterMessage(C2SArenaEnter)

C2SArenaToplist = _reflection.GeneratedProtocolMessageType('C2SArenaToplist', (_message.Message,), dict(
  DESCRIPTOR = _C2SARENATOPLIST,
  __module__ = 'MessageArena_pb2'
  # @@protoc_insertion_point(class_scope:Message.C2SArenaToplist)
  ))
_sym_db.RegisterMessage(C2SArenaToplist)

C2SArenaRankPrize = _reflection.GeneratedProtocolMessageType('C2SArenaRankPrize', (_message.Message,), dict(
  DESCRIPTOR = _C2SARENARANKPRIZE,
  __module__ = 'MessageArena_pb2'
  # @@protoc_insertion_point(class_scope:Message.C2SArenaRankPrize)
  ))
_sym_db.RegisterMessage(C2SArenaRankPrize)

S2CArenaToplist = _reflection.GeneratedProtocolMessageType('S2CArenaToplist', (_message.Message,), dict(
  DESCRIPTOR = _S2CARENATOPLIST,
  __module__ = 'MessageArena_pb2'
  # @@protoc_insertion_point(class_scope:Message.S2CArenaToplist)
  ))
_sym_db.RegisterMessage(S2CArenaToplist)

S2CArenaTargetlist = _reflection.GeneratedProtocolMessageType('S2CArenaTargetlist', (_message.Message,), dict(
  DESCRIPTOR = _S2CARENATARGETLIST,
  __module__ = 'MessageArena_pb2'
  # @@protoc_insertion_point(class_scope:Message.S2CArenaTargetlist)
  ))
_sym_db.RegisterMessage(S2CArenaTargetlist)

S2CArenaPlayerInfo = _reflection.GeneratedProtocolMessageType('S2CArenaPlayerInfo', (_message.Message,), dict(
  DESCRIPTOR = _S2CARENAPLAYERINFO,
  __module__ = 'MessageArena_pb2'
  # @@protoc_insertion_point(class_scope:Message.S2CArenaPlayerInfo)
  ))
_sym_db.RegisterMessage(S2CArenaPlayerInfo)


# @@protoc_insertion_point(module_scope)
