# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageMail.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageMail.proto',
  package='Message',
  serialized_pb=_b('\n\x11MessageMail.proto\x12\x07Message\"+\n\x08MailCoin\x12\x10\n\x08\x63urrency\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"&\n\x08MailProp\x12\x0b\n\x03tid\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"\x9e\x01\n\x04Mail\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0e\n\x06\x65xpiry\x18\x03 \x01(\t\x12\x0c\n\x04read\x18\x04 \x01(\x08\x12\x0e\n\x06\x66romid\x18\x05 \x01(\t\x12#\n\x08\x63oinlist\x18\x06 \x03(\x0b\x32\x11.Message.MailCoin\x12#\n\x08proplist\x18\x07 \x03(\x0b\x32\x11.Message.MailProp\"\xa5\x01\n\x0b\x43\x32SMailSend\x12\x0e\n\x06\x66romid\x18\x01 \x01(\t\x12\x0c\n\x04toid\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x0e\n\x06\x65xpiry\x18\x05 \x01(\x05\x12#\n\x08\x63oinlist\x18\x06 \x03(\x0b\x32\x11.Message.MailCoin\x12#\n\x08proplist\x18\x07 \x03(\x0b\x32\x11.Message.MailProp\"\x1c\n\x0b\x43\x32SMailRead\x12\r\n\x05index\x18\x01 \x01(\x05\"\x1e\n\rC2SMailDelete\x12\r\n\x05index\x18\x01 \x01(\x05\"\x1f\n\x0e\x43\x32SMailExtract\x12\r\n\x05index\x18\x01 \x01(\x05\".\n\x0bS2CMailList\x12\x1f\n\x08maillist\x18\x01 \x03(\x0b\x32\r.Message.Mail')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MAILCOIN = _descriptor.Descriptor(
  name='MailCoin',
  full_name='Message.MailCoin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='currency', full_name='Message.MailCoin.currency', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='Message.MailCoin.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=73,
)


_MAILPROP = _descriptor.Descriptor(
  name='MailProp',
  full_name='Message.MailProp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tid', full_name='Message.MailProp.tid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='Message.MailProp.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=113,
)


_MAIL = _descriptor.Descriptor(
  name='Mail',
  full_name='Message.Mail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='Message.Mail.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='Message.Mail.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expiry', full_name='Message.Mail.expiry', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='read', full_name='Message.Mail.read', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fromid', full_name='Message.Mail.fromid', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coinlist', full_name='Message.Mail.coinlist', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='proplist', full_name='Message.Mail.proplist', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=274,
)


_C2SMAILSEND = _descriptor.Descriptor(
  name='C2SMailSend',
  full_name='Message.C2SMailSend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fromid', full_name='Message.C2SMailSend.fromid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='toid', full_name='Message.C2SMailSend.toid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='Message.C2SMailSend.title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='Message.C2SMailSend.content', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expiry', full_name='Message.C2SMailSend.expiry', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coinlist', full_name='Message.C2SMailSend.coinlist', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='proplist', full_name='Message.C2SMailSend.proplist', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=442,
)


_C2SMAILREAD = _descriptor.Descriptor(
  name='C2SMailRead',
  full_name='Message.C2SMailRead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='Message.C2SMailRead.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=444,
  serialized_end=472,
)


_C2SMAILDELETE = _descriptor.Descriptor(
  name='C2SMailDelete',
  full_name='Message.C2SMailDelete',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='Message.C2SMailDelete.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=474,
  serialized_end=504,
)


_C2SMAILEXTRACT = _descriptor.Descriptor(
  name='C2SMailExtract',
  full_name='Message.C2SMailExtract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='Message.C2SMailExtract.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=506,
  serialized_end=537,
)


_S2CMAILLIST = _descriptor.Descriptor(
  name='S2CMailList',
  full_name='Message.S2CMailList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='maillist', full_name='Message.S2CMailList.maillist', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=539,
  serialized_end=585,
)

_MAIL.fields_by_name['coinlist'].message_type = _MAILCOIN
_MAIL.fields_by_name['proplist'].message_type = _MAILPROP
_C2SMAILSEND.fields_by_name['coinlist'].message_type = _MAILCOIN
_C2SMAILSEND.fields_by_name['proplist'].message_type = _MAILPROP
_S2CMAILLIST.fields_by_name['maillist'].message_type = _MAIL
DESCRIPTOR.message_types_by_name['MailCoin'] = _MAILCOIN
DESCRIPTOR.message_types_by_name['MailProp'] = _MAILPROP
DESCRIPTOR.message_types_by_name['Mail'] = _MAIL
DESCRIPTOR.message_types_by_name['C2SMailSend'] = _C2SMAILSEND
DESCRIPTOR.message_types_by_name['C2SMailRead'] = _C2SMAILREAD
DESCRIPTOR.message_types_by_name['C2SMailDelete'] = _C2SMAILDELETE
DESCRIPTOR.message_types_by_name['C2SMailExtract'] = _C2SMAILEXTRACT
DESCRIPTOR.message_types_by_name['S2CMailList'] = _S2CMAILLIST

MailCoin = _reflection.GeneratedProtocolMessageType('MailCoin', (_message.Message,), dict(
  DESCRIPTOR = _MAILCOIN,
  __module__ = 'MessageMail_pb2'
  # @@protoc_insertion_point(class_scope:Message.MailCoin)
  ))
_sym_db.RegisterMessage(MailCoin)

MailProp = _reflection.GeneratedProtocolMessageType('MailProp', (_message.Message,), dict(
  DESCRIPTOR = _MAILPROP,
  __module__ = 'MessageMail_pb2'
  # @@protoc_insertion_point(class_scope:Message.MailProp)
  ))
_sym_db.RegisterMessage(MailProp)

Mail = _reflection.GeneratedProtocolMessageType('Mail', (_message.Message,), dict(
  DESCRIPTOR = _MAIL,
  __module__ = 'MessageMail_pb2'
  # @@protoc_insertion_point(class_scope:Message.Mail)
  ))
_sym_db.RegisterMessage(Mail)

C2SMailSend = _reflection.GeneratedProtocolMessageType('C2SMailSend', (_message.Message,), dict(
  DESCRIPTOR = _C2SMAILSEND,
  __module__ = 'MessageMail_pb2'
  # @@protoc_insertion_point(class_scope:Message.C2SMailSend)
  ))
_sym_db.RegisterMessage(C2SMailSend)

C2SMailRead = _reflection.GeneratedProtocolMessageType('C2SMailRead', (_message.Message,), dict(
  DESCRIPTOR = _C2SMAILREAD,
  __module__ = 'MessageMail_pb2'
  # @@protoc_insertion_point(class_scope:Message.C2SMailRead)
  ))
_sym_db.RegisterMessage(C2SMailRead)

C2SMailDelete = _reflection.GeneratedProtocolMessageType('C2SMailDelete', (_message.Message,), dict(
  DESCRIPTOR = _C2SMAILDELETE,
  __module__ = 'MessageMail_pb2'
  # @@protoc_insertion_point(class_scope:Message.C2SMailDelete)
  ))
_sym_db.RegisterMessage(C2SMailDelete)

C2SMailExtract = _reflection.GeneratedProtocolMessageType('C2SMailExtract', (_message.Message,), dict(
  DESCRIPTOR = _C2SMAILEXTRACT,
  __module__ = 'MessageMail_pb2'
  # @@protoc_insertion_point(class_scope:Message.C2SMailExtract)
  ))
_sym_db.RegisterMessage(C2SMailExtract)

S2CMailList = _reflection.GeneratedProtocolMessageType('S2CMailList', (_message.Message,), dict(
  DESCRIPTOR = _S2CMAILLIST,
  __module__ = 'MessageMail_pb2'
  # @@protoc_insertion_point(class_scope:Message.S2CMailList)
  ))
_sym_db.RegisterMessage(S2CMailList)


# @@protoc_insertion_point(module_scope)
