# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageCommon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageCommon.proto',
  package='Message',
  serialized_pb=_b('\n\x13MessageCommon.proto\x12\x07Message\"6\n\x08S2CError\x12\r\n\x05\x65rror\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\r\n\x05notes\x18\x03 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_S2CERROR = _descriptor.Descriptor(
  name='S2CError',
  full_name='Message.S2CError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='Message.S2CError.error', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='Message.S2CError.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notes', full_name='Message.S2CError.notes', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['S2CError'] = _S2CERROR

S2CError = _reflection.GeneratedProtocolMessageType('S2CError', (_message.Message,), dict(
  DESCRIPTOR = _S2CERROR,
  __module__ = 'MessageCommon_pb2'
  # @@protoc_insertion_point(class_scope:Message.S2CError)
  ))
_sym_db.RegisterMessage(S2CError)


# @@protoc_insertion_point(module_scope)
